[project]
name = "cdk-docker-demo"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "aws-cdk-app-staging-synthesizer-alpha (>=2.207.0a0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "cdk_docker_demo", from = "src"}, {include = "cdk_docker_demo_stack", from = "stack"}]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.group.stack.dependencies]
aws-cdk-lib = "^2.189.0"
constructs = "^10.4.2"
aws-cdk-aws-lambda-python-alpha = "^2.189.0a0"
jsii = "^1.111.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.5"

